ALTER TABLE `CM_THIRDPART` ADD COLUMN `WECHAT_LOGIN_ENABLED` tinyint NOT NULL DEFAULT 0 COMMENT '微信生态自动登录开关' AFTER `HOME_URL`,
  ADD COLUMN `WECHAT_TYPE` varchar(20) DEFAULT NULL COMMENT '微信登录类型: agent 或 mp' AFTER `WECHAT_LOGIN_ENABLED`,
  ADD COLUMN `WECHAT_KEY` varchar(100) DEFAULT NULL COMMENT '企业号应用 key 或服务号 mpKey' AFTER `WECHAT_TYPE`,
  ADD COLUMN `WECHAT_SCOPE` varchar(50) DEFAULT NULL COMMENT '服务号 OAuth scope' AFTER `WECHAT_KEY`;
